apiVersion: v1
entries:
  typesense:
  - apiVersion: v2
    created: "2025-11-13T04:36:14.652051918Z"
    description: Typesense is an open-source search engine optimized for speed and
      typo-tolerance, delivering fast and relevant search results.
    digest: 55cbd095b7e8149120a9a1814f700bb2464b2c39446fd3c1486062dde1783056
    home: https://typesense.org/
    icon: https://typesense.org/assets/images/typesense_medium.png
    keywords:
    - search
    name: typesense
    sources:
    - https://github.com/typesense/typesense
    urls:
    - https://kahf-infra.github.io/typesense-helm/charts/typesense-1.0.15.tgz
    version: 1.0.15
generated: "2025-11-13T04:36:14.651479667Z"
